# Generated by Django 5.1 on 2024-08-28 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Üye Rolü")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Kategori"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("is_public", models.BooleanField(default=True, verbose_name="Genel")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Üye Rolü",
                "verbose_name_plural": "Üye Rolleri",
            },
        ),
        migrations.CreateModel(
            name="MemberTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Üye Tipi")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Kategori"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("is_public", models.BooleanField(default=True, verbose_name="Genel")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Üye Tipi",
                "verbose_name_plural": "Üye Tipleri",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Şirket Adı")),
                (
                    "slug",
                    models.SlugField(
                        max_length=256, unique=True, verbose_name="Şirket Slug"
                    ),
                ),
                (
                    "is_branch",
                    models.BooleanField(default=False, verbose_name="Şube Mi?"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Şirket Tipi",
                    ),
                ),
                (
                    "hierarchy",
                    models.PositiveIntegerField(default=0, verbose_name="Hiyerarşi"),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Geçerlilik Başlangıç Tarihi",
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Geçerlilik Bitiş Tarihi"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ödenen Tutar",
                    ),
                ),
                (
                    "paid_currency",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Para Birimi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "bill_comp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bill_companies",
                        to="_BASE.company",
                        verbose_name="Fatura Şirketi",
                    ),
                ),
                (
                    "manager_comp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager_companies",
                        to="_BASE.company",
                        verbose_name="Yönetim Şirketi",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_companies",
                        to="_BASE.company",
                        verbose_name="Bağlı Olduğu Şirket",
                    ),
                ),
                (
                    "supplier_comp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_companies",
                        to="_BASE.company",
                        verbose_name="Tedarikçi Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şirket",
                "verbose_name_plural": "Şirketler",
            },
        ),
        migrations.CreateModel(
            name="CompanyAdditionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tax_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Vergi Numarası",
                    ),
                ),
                (
                    "tax_office",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Vergi Dairesi",
                    ),
                ),
                (
                    "mernis_no",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Mernis Numarası",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        default="Türkiye",
                        max_length=50,
                        null=True,
                        verbose_name="Ülke",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Şehir"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="İlçe"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Adres"),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Posta Kodu"
                    ),
                ),
                (
                    "auth_firstname",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Yetkili Kişi Adı",
                    ),
                ),
                (
                    "auth_lastname",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Yetkili Kişi Syoadı",
                    ),
                ),
                (
                    "auth_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Yetkili Kişi Telefon",
                    ),
                ),
                (
                    "auth_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Yetkili Kişi E-Posta",
                    ),
                ),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_additional_info",
                        to="_BASE.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şirket Ek Bilgisi",
                "verbose_name_plural": "Şirket Ek Bilgileri",
            },
        ),
        migrations.CreateModel(
            name="CompanyServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, verbose_name="Servis Adı")),
                (
                    "service",
                    models.CharField(
                        choices=[("Ecom", "Ecom"), ("Dashboard", "Dashboard")],
                        max_length=255,
                        verbose_name="Servis",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True, null=True, verbose_name="Geçerlilik Tarihi"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ödenen Tutar",
                    ),
                ),
                (
                    "paid_currency",
                    models.CharField(
                        blank=True, max_length=3, null=True, verbose_name="Para Birimi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_services",
                        to="_BASE.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şirket Servisi",
                "verbose_name_plural": "Şirket Servisleri",
            },
        ),
        migrations.CreateModel(
            name="CompanyServiceDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.URLField(verbose_name="Domain")),
                (
                    "subdomain",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="Subdomain",
                    ),
                ),
                (
                    "directory",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=50,
                        null=True,
                        verbose_name="Yol",
                    ),
                ),
                ("complete_domain", models.URLField(editable=False, max_length=255)),
                (
                    "complete_path",
                    models.URLField(editable=False, max_length=255, unique=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_service_domain",
                        to="_BASE.company",
                    ),
                ),
                (
                    "company_service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_service_domain",
                        to="_BASE.companyservices",
                    ),
                ),
            ],
            options={
                "verbose_name": "Şirket Servis Domaini",
                "verbose_name_plural": "Şirket Servis Domainleri",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="paid_services",
            field=models.ManyToManyField(
                blank=True,
                related_name="paid_servies",
                to="_BASE.companyservices",
                verbose_name="Ödenen Servisler",
            ),
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Kullanıcı Adı",
                    ),
                ),
                (
                    "firstname",
                    models.CharField(max_length=1000, verbose_name="Üye Adı"),
                ),
                (
                    "middlename",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Üye Orta Adı",
                    ),
                ),
                (
                    "lastname",
                    models.CharField(max_length=1000, verbose_name="Üye Soyadı"),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="members/profile_pictures",
                        verbose_name="Profil Resmi",
                    ),
                ),
                (
                    "idtax_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="TC/Vergi No"
                    ),
                ),
                (
                    "tax_office",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Vergi Dairesi",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=1000, null=True, verbose_name="E-Posta"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cinsiyet"
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarihi"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ağırlık",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Boy",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Adresi"
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Sezon"
                    ),
                ),
                (
                    "registration_state",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Kayıt Durumu",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Açıklama"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Giriş"
                    ),
                ),
                (
                    "additional_data",
                    models.JSONField(blank=True, null=True, verbose_name="Ek Veri"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_members",
                        to="_BASE.company",
                        verbose_name="Şirket",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
                (
                    "member_role",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Üye ile ilişkilendirilmiş üye rolleri",
                        related_name="member_user_roles",
                        to="_BASE.memberroles",
                        verbose_name="Üye Rolleri",
                    ),
                ),
            ],
            options={
                "verbose_name": "Üye",
                "verbose_name_plural": "Üyeler",
            },
        ),
        migrations.CreateModel(
            name="MemberAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Delivery", "Teslimat"), ("Invoice", "Fatura")],
                        default="Delivery",
                        max_length=100,
                        verbose_name="Adres Tipi",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=255, verbose_name="Alıcı Adı"),
                ),
                (
                    "recipient_lastname",
                    models.CharField(max_length=255, verbose_name="Alıcı Soyadı"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Türkiye", max_length=100, verbose_name="Ülke"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Şehir")),
                ("district", models.CharField(max_length=100, verbose_name="İlçe")),
                ("full_address", models.TextField(verbose_name="Adres")),
                (
                    "postal_code",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Posta Kodu"
                    ),
                ),
                ("phone", models.IntegerField(verbose_name="Telefon Numarası")),
                ("email", models.EmailField(max_length=254, verbose_name="E-Posta")),
                (
                    "comp_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Şirket Adı"
                    ),
                ),
                (
                    "tax_office",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Vergi Dairesi",
                    ),
                ),
                (
                    "tax_no",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="Vergi Numarası"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_addresses",
                        to="_BASE.member",
                        verbose_name="Üye",
                    ),
                ),
            ],
            options={
                "verbose_name": "Üye Adresi",
                "verbose_name_plural": "Üye Adresleri",
            },
        ),
        migrations.CreateModel(
            name="MemberTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=1000, verbose_name="Etiket")),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=1000, null=True, verbose_name="Kategori"
                    ),
                ),
                (
                    "visibility",
                    models.BooleanField(default=True, verbose_name="Görünürlük"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_member_tags",
                        to="_BASE.company",
                        verbose_name="Şirket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Üye Etiketi",
                "verbose_name_plural": "Üye Etiketleri",
            },
        ),
        migrations.AddField(
            model_name="member",
            name="member_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Üye ile ilişkilendirilmiş kullanıcı etiketleri",
                related_name="member_user_tags",
                to="_BASE.membertags",
                verbose_name="Kullanıcı Etiketleri",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="member_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Şirket ile ilişkilendirilmiş üye etiketleri",
                related_name="company_member_tags",
                to="_BASE.membertags",
                verbose_name="Üye Etiketleri",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="member_type",
            field=models.ManyToManyField(
                blank=True,
                help_text="Üye ile ilişkilendirilmiş üye tipleri",
                related_name="member_user_types",
                to="_BASE.membertypes",
                verbose_name="Üye Tipleri",
            ),
        ),
    ]
